workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.guptaankit9.ankitproject"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install expo-cli@6.3.0
          npm install
      - name: Install sharp-cli globally
        script: |
          npm install -g sharp-cli
      - name: Install compatible expo-system-ui version
        script: |
          npm install expo-system-ui@3.0.0

      - name: Validate Metro Configuration
        script: |
          if [ ! -f metro.config.js ]; then
            echo "module.exports = require('@expo/metro-config').getDefaultConfig(__dirname);" > metro.config.js
          fi
      - name: Validate Expo project setup
        script: |
          npx expo-doctor || true
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild
      - name: Build Android release
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false